name: publish
on: [push]
jobs:
publish-gologol-api-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ secrets.ACTOR }}
password: ${{ secrets.THE_TOKEN }}
- name: Build the gologol-api Docker image
run: |
       docker build . --tag ghcr.io/villenams/gologol-api-gcr:latest
       docker run ghcr.io/villenams/gologol-api-gcr:latest
       docker push ghcr.io/villenams/gologol-api-gcr:latest